use bankanalytics;
RENAME TABLE `BANKING DATASET G3` TO `BANKING_DATASET`;
SELECT * FROM BANKING_DATASET;

/*TOTAL LOAN AMOUNT FUNDED*/
SELECT sum(funded_amount) as funded_amt FROM BANKING_DATASET;

/*TOTAL LOANS*/
SELECT COUNT(*) AS total_loans from banking_dataset;

/*STATE WISE LOAN*/
SELECT STATE_ABBR, COUNT(*) AS STATE_WISE_LOAN FROM BANKING_DATASET
GROUP BY STATE_ABBR
ORDER BY STATE_WISE_LOAN DESC;

/*GRRADE WISE LOAN*/
SELECT GRRADE ,COUNT(*) AS GRADE_WISE_LOAN
FROM BANKING_DATASET 
GROUP BY GRRADE ORDER BY GRADE_WISE_LOAN DESC;

/*TOTAL COLLECTION*/
SELECT SUM(RECOVERIES) AS TOTAL_COLLECTION 
FROM BANKING_DATASET;

/*RELIGION WISE LOAN*/
SELECT RELIGION, COUNT(*) AS RELIGION_WISE_LOAN
FROM BANKING_DATASET GROUP BY RELIGION 
ORDER BY RELIGION_WISE_LOAN DESC;




